staging: qcacld-3.0: disable some build warnings
Disable unused-but-set-variable and array-parameter warnings for Clang
to pass the build.

CC drivers/staging/qcacld-3.0/../qca-wifi-host-cmn/qdf/linux/src/qdf_debugfs.o
../drivers/staging/qcacld-3.0/core/mac/src/sys/legacy/src/utils/src/parser_api.c:4109:10:
warning: variable 'rfBand' set but not used [-Wunused-but-set-variable]
 4109 |         uint8_t rfBand;
      |                 ^
../drivers/staging/qcacld-3.0/core/mac/src/sys/legacy/src/utils/src/parser_api.c:6058:14:
error: argument 'mdie' of type 'uint8_t[3]' (aka 'unsigned char[3]')
with mismatched bound [-Werror,-Warray-parameter]
 6058 |                    uint8_t mdie[SIR_MDIE_SIZE])
      |                                 ^

Signed-off-by: Linhui Liu <liulinhui36@gmail.com>